quality  gate 50%

diff --git a/.github/workflows/run-api-tests.yaml b/.github/workflows/run-api-tests.yaml
--- a/.github/workflows/run-api-tests.yaml
+++ b/.github/workflows/run-api-tests.yaml
@@ -172,6 +172,23 @@ jobs:
 
           sudo cp swagger-coverage-report.html \
             allure-history/swagger-coverage-report.html
+
+      - name: Check Swagger coverage quality gate
+        if: always()
+        run: |
+          THRESHOLD=5
+      
+          TOTAL=$(jq '.operations | length' swagger-coverage-results.json)
+          FULL=$(jq '[.operations[] | select(.state == "FULL")] | length' swagger-coverage-results.json)
+      
+          PERCENT=$(( FULL * 100 / TOTAL ))
+      
+          echo "Full coverage = ${PERCENT}%"
+      
+          if [ "$PERCENT" -lt "$THRESHOLD" ]; then
+          echo "Quality gate failed"
+          exit 1
+          fi
       
 
 #
